name: quizzly
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # for pouring confetti at the end
  confetti: ^0.7.0

  # for glowing around the total score
  avatar_glow: ^2.0.2

  # for localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Expletus
      fonts:
        - asset: assets/fonts/ExpletusSans-VariableFont_wght.ttf

    - family: DM
      fonts:
        - asset: assets/fonts/DMSans-VariableFont_opsz,wght.ttf

